name: build
on: [push]

env:
    VERSION_PREFIX: "3.0.0"

jobs:
    build:
        runs-on: [ubuntu-latest]

        steps:

          - uses: Brightspace/third-party-actions@actions/checkout

          - name: Setup .NET Core
            uses:  Brightspace/third-party-actions@actions/setup-dotnet
            with:
                dotnet-version: 5.0.x

          - name: dotnet tool restore
            run: dotnet tool restore

          - name: Generate version properties
            run: dotnet ci-version-properties --output VersionInfo.props && cat VersionInfo.props

          - name: dotnet restore
            run: dotnet restore

          - name: dotnet build
            run: dotnet build --configuration Release

          - name: dotnet test
            run: dotnet test --configuration Release --no-build

          - name: dotnet pack
            run: dotnet pack --configuration Release --no-build

          - run: mkdir dist/
          - run: cp src/SimpleLogInterface/bin/Release/*.nupkg dist/
          - run: cp src/SimpleLogInterface.Log4Net/bin/Release/*.nupkg dist/
          - run: cp src/SimpleLogInterface.NUnit/bin/Release/*.nupkg dist/

          - name: Archive dist/
            uses: actions/upload-artifact@v1
            with:
                name: dist
                path: dist/

