name: "Commit"

on:
  push:
    branches:
      - master

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}

jobs:
  Publish:
    runs-on: windows-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - uses: Brightspace/codeartifact-actions/nuget/add-source@v1.0.0
        with:
          nuget-config-path: ./.nuget/NuGet.Config
      - name: Run Windows Build, Package and Publish
        run: ./build.ps1 -Publish
        shell: powershell

