name: "Preflight"

on: pull_request

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: Brightspace/third-party-actions@actions/checkout
      - name: Run Windows Preflight
        run: ./build.ps1
        shell: powershell
